import type { GardenPlantCatalogEntry } from "./types";

const RAW_GARDEN_PLANT_CATALOG: GardenPlantCatalogEntry[] = [
  {
    kind: "garden",
    common: "Cabbage",
    latin: "Brassica oleracea var. capitata",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-15", "04-01"],
    sow_outdoors: ["03-15", "05-01"],
    harvest_window: ["06-15", "10-01"],
    spacing_cm: 45,
    frost_sensitive: false,
    summary: "Heading brassica grown for dense leafy heads; enjoys fertile, moisture-retentive soil.",
  },
  {
    kind: "garden",
    common: "Broccoli",
    latin: "Brassica oleracea var. italica",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-20", "04-10"],
    sow_outdoors: ["03-25", "05-10"],
    harvest_window: ["06-20", "10-30"],
    spacing_cm: 45,
    frost_sensitive: false,
    summary: "Produces central heads followed by side shoots; steady moisture prevents bitterness.",
  },
  {
    kind: "garden",
    common: "Cauliflower",
    latin: "Brassica oleracea var. botrytis",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-20", "04-05"],
    sow_outdoors: ["03-25", "05-05"],
    harvest_window: ["07-01", "10-15"],
    spacing_cm: 50,
    frost_sensitive: false,
    summary: "Compact white curds benefit from rich soil and blanching leaves over heads in sun.",
  },
  {
    kind: "garden",
    common: "Brussels sprouts",
    latin: "Brassica oleracea var. gemmifera",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-20", "04-01"],
    sow_outdoors: ["03-25", "04-25"],
    harvest_window: ["09-15", "02-01"],
    spacing_cm: 60,
    frost_sensitive: false,
    summary: "Tall stems studded with sprouts; cool weather improves sweetness and texture.",
  },
  {
    kind: "garden",
    common: "Kale",
    latin: "Brassica oleracea var. acephala",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-15", "04-15"],
    sow_outdoors: ["03-20", "07-15"],
    harvest_window: ["06-15", "03-01"],
    spacing_cm: 40,
    frost_sensitive: false,
    summary: "Leafy brassica for repeated harvests; frost enhances flavor and texture.",
  },
  {
    kind: "garden",
    common: "Collard greens",
    latin: "Brassica oleracea var. viridis",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-20", "04-20"],
    sow_outdoors: ["03-25", "07-20"],
    harvest_window: ["06-15", "02-28"],
    spacing_cm: 45,
    frost_sensitive: false,
    summary: "Heat- and cold-tolerant leaves for braising; continuous picking encourages new growth.",
  },
  {
    kind: "garden",
    common: "Savoy cabbage",
    latin: "Brassica oleracea var. sabauda",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-25", "04-10"],
    sow_outdoors: ["03-30", "05-10"],
    harvest_window: ["07-15", "11-15"],
    spacing_cm: 45,
    frost_sensitive: false,
    summary: "Crinkled leaves form loose heads; excellent for autumn harvest and slaws.",
  },
  {
    kind: "garden",
    common: "Napa cabbage",
    latin: "Brassica rapa subsp. pekinensis",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["03-01", "04-15"],
    sow_outdoors: ["03-25", "07-25"],
    harvest_window: ["06-20", "10-15"],
    spacing_cm: 35,
    frost_sensitive: false,
    summary: "Elongated heads with tender leaves; grows fast in cool spring or late summer.",
  },
  {
    kind: "garden",
    common: "Bok choy",
    latin: "Brassica rapa subsp. chinensis",
    family: "brassicas",
    sun: "partial-sun",
    sow_indoors: ["02-25", "05-01"],
    sow_outdoors: ["03-20", "08-20"],
    harvest_window: ["05-15", "10-30"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Pak choi with crisp petioles; prefers cool weather and steady moisture to avoid bolting.",
  },
  {
    kind: "garden",
    common: "Tatsoi",
    latin: "Brassica rapa var. rosularis",
    family: "brassicas",
    sun: "partial-sun",
    sow_indoors: ["03-01", "04-15"],
    sow_outdoors: ["03-20", "09-01"],
    harvest_window: ["05-10", "11-15"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Rosette-forming Asian green with spoon-shaped leaves that tolerate frost.",
  },
  {
    kind: "garden",
    common: "Mizuna",
    latin: "Brassica rapa var. nipposinica",
    family: "brassicas",
    sun: "partial-sun",
    sow_indoors: ["02-25", "04-20"],
    sow_outdoors: ["03-20", "09-10"],
    harvest_window: ["05-01", "11-01"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Frilly mustard green for salads and stir-fries; cut-and-come-again habit.",
  },
  {
    kind: "garden",
    common: "Mustard greens",
    latin: "Brassica juncea",
    family: "brassicas",
    sun: "partial-sun",
    sow_indoors: ["03-01", "04-15"],
    sow_outdoors: ["03-20", "09-15"],
    harvest_window: ["05-10", "11-20"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Peppery leaves best in cool weather; succession sow for steady supply.",
  },
  {
    kind: "garden",
    common: "Kohlrabi",
    latin: "Brassica oleracea var. gongylodes",
    family: "brassicas",
    sun: "full-sun",
    sow_indoors: ["02-25", "04-15"],
    sow_outdoors: ["03-20", "07-15"],
    harvest_window: ["06-01", "10-30"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Swollen stems harvested tennis-ball size for crisp, sweet flesh.",
  },
  {
    kind: "garden",
    common: "Garden pea",
    latin: "Pisum sativum",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["03-01", "05-01"],
    harvest_window: ["05-25", "07-30"],
    spacing_cm: 5,
    frost_sensitive: false,
    summary: "Cool-season vine needing support; harvest pods when plump.",
  },
  {
    kind: "garden",
    common: "Sugar snap pea",
    latin: "Pisum sativum var. macrocarpon",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["03-05", "05-10"],
    harvest_window: ["06-01", "08-01"],
    spacing_cm: 5,
    frost_sensitive: false,
    summary: "Edible pods stay sweet and crisp; train on trellis and pick daily.",
  },
  {
    kind: "garden",
    common: "Snow pea",
    latin: "Pisum sativum var. saccharatum",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["03-05", "05-10"],
    harvest_window: ["05-25", "07-20"],
    spacing_cm: 5,
    frost_sensitive: false,
    summary: "Flat pods harvested before peas swell; thrives in cool climates.",
  },
  {
    kind: "garden",
    common: "Bush bean",
    latin: "Phaseolus vulgaris",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["05-10", "07-10"],
    harvest_window: ["07-01", "09-20"],
    spacing_cm: 10,
    frost_sensitive: true,
    summary: "Compact bean plants for repeated picking; avoid sowing until soil warms.",
  },
  {
    kind: "garden",
    common: "Pole bean",
    latin: "Phaseolus vulgaris var. vulgaris",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["05-15", "06-20"],
    harvest_window: ["07-15", "10-01"],
    spacing_cm: 15,
    frost_sensitive: true,
    summary: "Climbing beans needing sturdy supports; harvest regularly for tender pods.",
  },
  {
    kind: "garden",
    common: "Runner bean",
    latin: "Phaseolus coccineus",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["05-15", "06-20"],
    harvest_window: ["07-20", "10-10"],
    spacing_cm: 20,
    frost_sensitive: true,
    summary: "Vigorous climber with edible pods and ornamental blossoms; keep moist for heavy yields.",
  },
  {
    kind: "garden",
    common: "Lima bean",
    latin: "Phaseolus lunatus",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["05-20", "06-30"],
    harvest_window: ["08-01", "10-15"],
    spacing_cm: 20,
    frost_sensitive: true,
    summary: "Warm-season bean grown for starchy seeds; needs consistent warmth to mature.",
  },
  {
    kind: "garden",
    common: "Fava bean",
    latin: "Vicia faba",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["02-20", "04-10"],
    harvest_window: ["06-01", "07-30"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Cool-season bean with upright stems; pinch tops to deter blackfly.",
  },
  {
    kind: "garden",
    common: "Chickpea",
    latin: "Cicer arietinum",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["04-01", "05-15"],
    harvest_window: ["08-01", "09-15"],
    spacing_cm: 15,
    frost_sensitive: true,
    summary: "Bushy plants bearing pods with nutty chickpeas; thrives in warm, dry summers.",
  },
  {
    kind: "garden",
    common: "Lentil",
    latin: "Lens culinaris",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["03-20", "04-30"],
    harvest_window: ["07-20", "09-10"],
    spacing_cm: 10,
    frost_sensitive: false,
    summary: "Fine-textured plants grown for drying seed; requires free-draining soil.",
  },
  {
    kind: "garden",
    common: "Soybean",
    latin: "Glycine max",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["05-20", "06-30"],
    harvest_window: ["08-15", "10-05"],
    spacing_cm: 15,
    frost_sensitive: true,
    summary: "Edamame pods harvested green; needs warmth and moisture to fill seeds.",
  },
  {
    kind: "garden",
    common: "Black-eyed pea",
    latin: "Vigna unguiculata",
    family: "legumes",
    sun: "full-sun",
    sow_outdoors: ["05-25", "07-01"],
    harvest_window: ["08-15", "10-10"],
    spacing_cm: 15,
    frost_sensitive: true,
    summary: "Heat-loving southern pea for shelling or drying; tolerates drought once established.",
  },
  {
    kind: "garden",
    common: "Carrot",
    latin: "Daucus carota subsp. sativus",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["03-20", "07-20"],
    harvest_window: ["06-20", "11-30"],
    spacing_cm: 4,
    frost_sensitive: false,
    summary: "Tap-root crop needing stone-free soil; thin seedlings for straight roots.",
  },
  {
    kind: "garden",
    common: "Beetroot",
    latin: "Beta vulgaris",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["03-25", "07-30"],
    harvest_window: ["06-15", "11-15"],
    spacing_cm: 8,
    frost_sensitive: false,
    summary: "Dual-purpose roots and greens; successive sowings give continuous harvest.",
  },
  {
    kind: "garden",
    common: "Radish",
    latin: "Raphanus sativus",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["03-15", "09-15"],
    harvest_window: ["04-15", "10-30"],
    spacing_cm: 3,
    frost_sensitive: false,
    summary: "Fast-maturing roots ideal for intercropping; keep soil moist to avoid pithiness.",
  },
  {
    kind: "garden",
    common: "Daikon radish",
    latin: "Raphanus sativus var. longipinnatus",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["07-15", "09-01"],
    harvest_window: ["09-15", "12-15"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Long white roots loosen soil; sow late summer for tender texture.",
  },
  {
    kind: "garden",
    common: "Turnip",
    latin: "Brassica rapa subsp. rapa",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["03-20", "09-10"],
    harvest_window: ["05-15", "11-30"],
    spacing_cm: 10,
    frost_sensitive: false,
    summary: "Dual-purpose greens and roots; rapid grower for early or late cropping.",
  },
  {
    kind: "garden",
    common: "Parsnip",
    latin: "Pastinaca sativa",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["02-25", "05-01"],
    harvest_window: ["09-01", "03-01"],
    spacing_cm: 8,
    frost_sensitive: false,
    summary: "Sweet, white roots best after frost; sow fresh seed directly in deep soil.",
  },
  {
    kind: "garden",
    common: "Rutabaga",
    latin: "Brassica napus var. napobrassica",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["05-01", "06-30"],
    harvest_window: ["09-15", "02-15"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Swedes form dense roots for winter storage; keep evenly moist to prevent cracking.",
  },
  {
    kind: "garden",
    common: "Sweet potato",
    latin: "Ipomoea batatas",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["05-20", "06-15"],
    harvest_window: ["09-15", "10-20"],
    spacing_cm: 30,
    frost_sensitive: true,
    summary: "Warm-season vine grown from slips; provide black plastic or cloches in cool climates.",
  },
  {
    kind: "garden",
    common: "Potato",
    latin: "Solanum tuberosum",
    family: "roots",
    sun: "full-sun",
    sow_outdoors: ["03-15", "05-15"],
    harvest_window: ["06-15", "10-15"],
    spacing_cm: 35,
    frost_sensitive: true,
    summary: "Tuber crop planted as seed potatoes; earth up stems to protect developing tubers.",
  },
  {
    kind: "garden",
    common: "Onion",
    latin: "Allium cepa",
    family: "alliums",
    sun: "full-sun",
    sow_indoors: ["02-10", "03-15"],
    sow_outdoors: ["03-15", "04-20"],
    harvest_window: ["07-01", "09-15"],
    spacing_cm: 10,
    frost_sensitive: false,
    summary: "Bulbing allium from seed or sets; dry thoroughly before storage.",
  },
  {
    kind: "garden",
    common: "Garlic",
    latin: "Allium sativum",
    family: "alliums",
    sun: "full-sun",
    sow_outdoors: ["10-01", "11-15"],
    harvest_window: ["06-15", "08-01"],
    spacing_cm: 12,
    frost_sensitive: false,
    summary: "Plant cloves in autumn for large heads; cure in shade after lifting.",
  },
  {
    kind: "garden",
    common: "Shallot",
    latin: "Allium cepa var. aggregatum",
    family: "alliums",
    sun: "full-sun",
    sow_outdoors: ["03-10", "04-20"],
    harvest_window: ["07-10", "08-20"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Cluster-forming allium with mild bulbs; plant sets shallowly in fertile soil.",
  },
  {
    kind: "garden",
    common: "Leek",
    latin: "Allium ampeloprasum var. porrum",
    family: "alliums",
    sun: "full-sun",
    sow_indoors: ["01-15", "03-15"],
    sow_outdoors: ["03-25", "05-10"],
    harvest_window: ["08-15", "04-01"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Mild allium with blanched stems; transplant deep and earth up for long shanks.",
  },
  {
    kind: "garden",
    common: "Scallion",
    latin: "Allium fistulosum",
    family: "alliums",
    sun: "full-sun",
    sow_outdoors: ["03-20", "08-15"],
    harvest_window: ["05-15", "10-30"],
    spacing_cm: 5,
    frost_sensitive: false,
    summary: "Perennial spring onion for repeated cutting; harvest young for tender stems.",
  },
  {
    kind: "garden",
    common: "Chive",
    latin: "Allium schoenoprasum",
    family: "alliums",
    sun: "partial-sun",
    sow_outdoors: ["03-25", "07-30"],
    harvest_window: ["05-01", "10-30"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Clump-forming herb with hollow leaves; attractive purple flowers feed pollinators.",
  },
  {
    kind: "garden",
    common: "Garlic chive",
    latin: "Allium tuberosum",
    family: "alliums",
    sun: "partial-sun",
    sow_outdoors: ["04-01", "06-15"],
    harvest_window: ["06-15", "10-30"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Flat-leaved allium with mild garlic flavor; flowers attract beneficial insects.",
  },
  {
    kind: "garden",
    common: "Ramps",
    latin: "Allium tricoccum",
    family: "alliums",
    sun: "shade",
    sow_outdoors: ["09-15", "11-15"],
    harvest_window: ["04-01", "05-20"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Wild leek preferring moist woodland soil; harvest sparingly to protect colonies.",
  },
  {
    kind: "garden",
    common: "Welsh onion",
    latin: "Allium fistulosum var. viviparum",
    family: "alliums",
    sun: "full-sun",
    sow_outdoors: ["03-20", "08-01"],
    harvest_window: ["05-20", "11-01"],
    spacing_cm: 20,
    frost_sensitive: false,
    summary: "Hardy perennial onion forming clumps; provides scallions from early spring.",
  },
  {
    kind: "garden",
    common: "Tomato",
    latin: "Solanum lycopersicum",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-20", "04-01"],
    sow_outdoors: ["05-15", "06-10"],
    harvest_window: ["07-10", "10-10"],
    spacing_cm: 60,
    frost_sensitive: true,
    summary: "Indeterminate vines require staking; remove suckers for larger fruit clusters.",
  },
  {
    kind: "garden",
    common: "Cherry tomato",
    latin: "Solanum lycopersicum var. cerasiforme",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-25", "04-05"],
    sow_outdoors: ["05-20", "06-10"],
    harvest_window: ["07-05", "10-20"],
    spacing_cm: 50,
    frost_sensitive: true,
    summary: "Prolific clusters of bite-sized fruit; ideal for containers and hanging baskets.",
  },
  {
    kind: "garden",
    common: "Roma tomato",
    latin: "Solanum lycopersicum 'Roma'",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-25", "04-05"],
    sow_outdoors: ["05-20", "06-05"],
    harvest_window: ["07-25", "10-15"],
    spacing_cm: 45,
    frost_sensitive: true,
    summary: "Determinate paste tomato great for sauces; grow in cages to support heavy fruit.",
  },
  {
    kind: "garden",
    common: "Bell pepper",
    latin: "Capsicum annuum",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-20", "03-30"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["07-20", "10-10"],
    spacing_cm: 40,
    frost_sensitive: true,
    summary: "Sweet peppers ripen from green to vivid colors; needs warmth and regular feeding.",
  },
  {
    kind: "garden",
    common: "Jalapeño pepper",
    latin: "Capsicum annuum 'Jalapeño'",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-20", "03-30"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["07-20", "10-10"],
    spacing_cm: 35,
    frost_sensitive: true,
    summary: "Moderately hot chilies for fresh or pickled use; harvest green or red.",
  },
  {
    kind: "garden",
    common: "Cayenne pepper",
    latin: "Capsicum annuum 'Cayenne'",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-20", "03-30"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["07-25", "10-15"],
    spacing_cm: 35,
    frost_sensitive: true,
    summary: "Slim hot peppers ideal for drying; pinch early flowers for stronger plants.",
  },
  {
    kind: "garden",
    common: "Habanero pepper",
    latin: "Capsicum chinense",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-01", "03-15"],
    sow_outdoors: ["05-25", "06-20"],
    harvest_window: ["08-01", "10-20"],
    spacing_cm: 40,
    frost_sensitive: true,
    summary: "Very hot peppers requiring long warm season; grow under cover in cool regions.",
  },
  {
    kind: "garden",
    common: "Eggplant",
    latin: "Solanum melongena",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["02-01", "03-15"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["07-25", "10-15"],
    spacing_cm: 45,
    frost_sensitive: true,
    summary: "Warm-season crop bearing glossy fruit; mulch to retain soil heat and moisture.",
  },
  {
    kind: "garden",
    common: "Tomatillo",
    latin: "Physalis philadelphica",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["03-01", "04-10"],
    sow_outdoors: ["05-20", "06-15"],
    harvest_window: ["08-01", "10-20"],
    spacing_cm: 50,
    frost_sensitive: true,
    summary: "Papery-husk fruit for salsa verde; grow at least two plants for pollination.",
  },
  {
    kind: "garden",
    common: "Ground cherry",
    latin: "Physalis pruinosa",
    family: "solanaceae",
    sun: "full-sun",
    sow_indoors: ["03-01", "04-10"],
    sow_outdoors: ["05-20", "06-20"],
    harvest_window: ["08-05", "10-20"],
    spacing_cm: 45,
    frost_sensitive: true,
    summary: "Sweet, pineapple-scented fruits drop when ripe; allow sprawling growth.",
  },
  {
    kind: "garden",
    common: "Cucumber",
    latin: "Cucumis sativus",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-10", "05-10"],
    sow_outdoors: ["05-25", "06-20"],
    harvest_window: ["07-01", "09-15"],
    spacing_cm: 40,
    frost_sensitive: true,
    summary: "Vining cucurbit needing warmth and plenty of water; trellis for straight fruit.",
  },
  {
    kind: "garden",
    common: "Zucchini",
    latin: "Cucurbita pepo",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-15", "05-10"],
    sow_outdoors: ["05-25", "06-30"],
    harvest_window: ["07-01", "10-15"],
    spacing_cm: 90,
    frost_sensitive: true,
    summary: "Prolific summer squash; harvest regularly to keep plants producing.",
  },
  {
    kind: "garden",
    common: "Yellow summer squash",
    latin: "Cucurbita pepo var. recticollis",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-15", "05-10"],
    sow_outdoors: ["05-25", "06-30"],
    harvest_window: ["07-01", "10-10"],
    spacing_cm: 90,
    frost_sensitive: true,
    summary: "Crookneck or straightneck squash harvested tender; needs insect pollination.",
  },
  {
    kind: "garden",
    common: "Pumpkin",
    latin: "Cucurbita pepo",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-20", "05-10"],
    sow_outdoors: ["05-25", "06-10"],
    harvest_window: ["09-15", "10-31"],
    spacing_cm: 120,
    frost_sensitive: true,
    summary: "Sprawling vines producing large fruit; cure skins before storage.",
  },
  {
    kind: "garden",
    common: "Butternut squash",
    latin: "Cucurbita moschata",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-15", "05-05"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["09-10", "10-31"],
    spacing_cm: 120,
    frost_sensitive: true,
    summary: "Long-keeping winter squash with sweet orange flesh; needs long warm season.",
  },
  {
    kind: "garden",
    common: "Acorn squash",
    latin: "Cucurbita pepo var. turbinata",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-15", "05-05"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["09-01", "10-20"],
    spacing_cm: 100,
    frost_sensitive: true,
    summary: "Compact winter squash with ribbed fruit; ideal for smaller gardens.",
  },
  {
    kind: "garden",
    common: "Spaghetti squash",
    latin: "Cucurbita pepo var. fastigata",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-15", "05-05"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["09-01", "10-20"],
    spacing_cm: 110,
    frost_sensitive: true,
    summary: "Flesh separates into strands after cooking; allow fruit to fully mature on vine.",
  },
  {
    kind: "garden",
    common: "Watermelon",
    latin: "Citrullus lanatus",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-10", "05-01"],
    sow_outdoors: ["05-25", "06-15"],
    harvest_window: ["08-10", "09-30"],
    spacing_cm: 150,
    frost_sensitive: true,
    summary: "Sweet melons requiring heat and abundant water; mulch to retain soil warmth.",
  },
  {
    kind: "garden",
    common: "Cantaloupe",
    latin: "Cucumis melo var. cantalupensis",
    family: "cucurbits",
    sun: "full-sun",
    sow_indoors: ["04-15", "05-05"],
    sow_outdoors: ["05-30", "06-20"],
    harvest_window: ["08-05", "09-25"],
    spacing_cm: 120,
    frost_sensitive: true,
    summary: "Netted melons that slip from vine when ripe; ensure pollination for full-sized fruit.",
  },
  {
    kind: "garden",
    common: "Lettuce",
    latin: "Lactuca sativa",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-10", "09-15"],
    harvest_window: ["05-01", "11-10"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Versatile leafy crop; succession sow and provide shade cloth in summer.",
  },
  {
    kind: "garden",
    common: "Romaine lettuce",
    latin: "Lactuca sativa var. longifolia",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["03-20", "08-20"],
    harvest_window: ["05-20", "10-31"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Upright heads with crunchy ribs; cool nights prevent bolting and bitterness.",
  },
  {
    kind: "garden",
    common: "Butterhead lettuce",
    latin: "Lactuca sativa var. capitata",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-10", "09-10"],
    harvest_window: ["05-10", "11-05"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Soft-leaved lettuce forming loose heads; ideal for cool-season tunnels.",
  },
  {
    kind: "garden",
    common: "Spinach",
    latin: "Spinacia oleracea",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-01", "05-15"],
    harvest_window: ["04-15", "06-30"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Tender leaves for salads; bolts quickly in heat, so sow in spring and autumn.",
  },
  {
    kind: "garden",
    common: "Swiss chard",
    latin: "Beta vulgaris var. cicla",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["03-25", "07-30"],
    harvest_window: ["06-01", "11-30"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Colorful stems and dark leaves withstand heat; cut outer stalks for regrowth.",
  },
  {
    kind: "garden",
    common: "Arugula",
    latin: "Eruca vesicaria",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-20", "09-30"],
    harvest_window: ["05-01", "11-15"],
    spacing_cm: 10,
    frost_sensitive: false,
    summary: "Peppery leaves for salads and pizza; succession sow for tender greens.",
  },
  {
    kind: "garden",
    common: "Endive",
    latin: "Cichorium endivia",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "08-15"],
    harvest_window: ["07-01", "10-31"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Bitter greens for salads; blanch inner leaves by tying heads a week before harvest.",
  },
  {
    kind: "garden",
    common: "Escarole",
    latin: "Cichorium endivia var. latifolia",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-20", "08-20"],
    harvest_window: ["07-10", "11-10"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Broad-leaved chicory with mild flavor; thrives in cool moist soil.",
  },
  {
    kind: "garden",
    common: "Radicchio",
    latin: "Cichorium intybus var. foliosum",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["06-15", "08-15"],
    harvest_window: ["09-15", "12-15"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Bitter Italian chicory forming burgundy heads; cool nights develop color.",
  },
  {
    kind: "garden",
    common: "Celery",
    latin: "Apium graveolens var. dulce",
    family: "misc",
    sun: "full-sun",
    sow_indoors: ["02-01", "03-15"],
    sow_outdoors: ["05-01", "05-31"],
    harvest_window: ["08-15", "10-31"],
    spacing_cm: 25,
    frost_sensitive: true,
    summary: "Moisture-loving stalk crop; blanch by collaring stems for milder flavor.",
  },
  {
    kind: "garden",
    common: "Fennel",
    latin: "Foeniculum vulgare var. azoricum",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "07-15"],
    harvest_window: ["07-15", "10-31"],
    spacing_cm: 25,
    frost_sensitive: true,
    summary: "Bulbing fennel with anise flavor; avoid transplant shock to prevent bolting.",
  },
  {
    kind: "garden",
    common: "Dill",
    latin: "Anethum graveolens",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-01", "07-15"],
    harvest_window: ["06-01", "09-30"],
    spacing_cm: 15,
    frost_sensitive: true,
    summary: "Feathery herb for pickling; allow some plants to flower for beneficial insects.",
  },
  {
    kind: "garden",
    common: "Cilantro",
    latin: "Coriandrum sativum",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-15", "09-15"],
    harvest_window: ["05-01", "10-31"],
    spacing_cm: 10,
    frost_sensitive: false,
    summary: "Cool-season herb; succession sow to avoid bolting and harvest seeds as coriander.",
  },
  {
    kind: "garden",
    common: "Parsley",
    latin: "Petroselinum crispum",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-20", "07-30"],
    harvest_window: ["06-01", "11-30"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Biennial herb with curly or flat leaves; slow to germinate, so soak seed overnight.",
  },
  {
    kind: "garden",
    common: "Basil",
    latin: "Ocimum basilicum",
    family: "misc",
    sun: "full-sun",
    sow_indoors: ["03-15", "04-30"],
    sow_outdoors: ["05-25", "06-20"],
    harvest_window: ["06-20", "10-01"],
    spacing_cm: 30,
    frost_sensitive: true,
    summary: "Tender annual herb; pinch blooms to extend leafy growth and harvest often.",
  },
  {
    kind: "garden",
    common: "Sage",
    latin: "Salvia officinalis",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "05-30"],
    harvest_window: ["06-01", "11-01"],
    spacing_cm: 40,
    frost_sensitive: false,
    summary: "Woody perennial herb with aromatic leaves; prune annually to maintain vigor.",
  },
  {
    kind: "garden",
    common: "Thyme",
    latin: "Thymus vulgaris",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "06-30"],
    harvest_window: ["06-01", "10-31"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Low-growing herb ideal for borders; well-drained soil prevents winter rot.",
  },
  {
    kind: "garden",
    common: "Rosemary",
    latin: "Salvia rosmarinus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-20", "06-15"],
    harvest_window: ["06-15", "11-01"],
    spacing_cm: 60,
    frost_sensitive: true,
    summary: "Evergreen shrub in mild climates; grow in pots and overwinter indoors where cold.",
  },
  {
    kind: "garden",
    common: "Oregano",
    latin: "Origanum vulgare",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-20", "06-30"],
    harvest_window: ["06-15", "10-31"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Perennial culinary herb; cut stems before flowering for best flavor.",
  },
  {
    kind: "garden",
    common: "Mint",
    latin: "Mentha × piperita",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["04-15", "07-30"],
    harvest_window: ["06-01", "10-30"],
    spacing_cm: 40,
    frost_sensitive: false,
    summary: "Vigorous herb spreading by runners; grow in containers to prevent invasiveness.",
  },
  {
    kind: "garden",
    common: "Tarragon",
    latin: "Artemisia dracunculus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-20", "06-15"],
    harvest_window: ["06-15", "10-15"],
    spacing_cm: 45,
    frost_sensitive: false,
    summary: "French tarragon offers anise flavor; propagate by cuttings rather than seed.",
  },
  {
    kind: "garden",
    common: "Chervil",
    latin: "Anthriscus cerefolium",
    family: "misc",
    sun: "partial-shade",
    sow_outdoors: ["03-15", "08-30"],
    harvest_window: ["05-01", "10-31"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Delicate herb suited to cool moist beds; bolt resistant in partial shade.",
  },
  {
    kind: "garden",
    common: "Lemongrass",
    latin: "Cymbopogon citratus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["05-25", "06-30"],
    harvest_window: ["07-15", "10-15"],
    spacing_cm: 60,
    frost_sensitive: true,
    summary: "Tropical clumping grass grown for fragrant stalks; overwinter indoors in cold zones.",
  },
  {
    kind: "garden",
    common: "Bay laurel",
    latin: "Laurus nobilis",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "06-15"],
    harvest_window: ["06-01", "11-01"],
    spacing_cm: 100,
    frost_sensitive: true,
    summary: "Mediterranean evergreen shrub; prune into standards and shelter from frost.",
  },
  {
    kind: "garden",
    common: "Sorrel",
    latin: "Rumex acetosa",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-25", "07-30"],
    harvest_window: ["05-01", "10-31"],
    spacing_cm: 30,
    frost_sensitive: false,
    summary: "Perennial leafy herb with tangy leaves; cut back flower stalks to prolong harvest.",
  },
  {
    kind: "garden",
    common: "Watercress",
    latin: "Nasturtium officinale",
    family: "misc",
    sun: "partial-shade",
    sow_outdoors: ["04-01", "08-15"],
    harvest_window: ["05-15", "10-31"],
    spacing_cm: 15,
    frost_sensitive: false,
    summary: "Aquatic herb thriving in shallow flowing water; harvest frequently for tender growth.",
  },
  {
    kind: "garden",
    common: "Nasturtium",
    latin: "Tropaeolum majus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-25", "06-30"],
    harvest_window: ["06-15", "10-15"],
    spacing_cm: 30,
    frost_sensitive: true,
    summary: "Edible flowers and leaves with peppery bite; great companion plant for aphid control.",
  },
  {
    kind: "garden",
    common: "Sunflower",
    latin: "Helianthus annuus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-25", "06-15"],
    harvest_window: ["08-01", "10-15"],
    spacing_cm: 45,
    frost_sensitive: true,
    summary: "Tall annual with large blooms and edible seeds; attracts pollinators and birds.",
  },
  {
    kind: "garden",
    common: "Marigold",
    latin: "Tagetes erecta",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-20", "06-15"],
    harvest_window: ["06-15", "10-30"],
    spacing_cm: 30,
    frost_sensitive: true,
    summary: "Cheerful bedding annual deterring pests; blooms all season with deadheading.",
  },
  {
    kind: "garden",
    common: "Zinnia",
    latin: "Zinnia elegans",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-25", "06-20"],
    harvest_window: ["06-25", "10-15"],
    spacing_cm: 30,
    frost_sensitive: true,
    summary: "Cut-flower favorite with bold colors; thrives in heat and well-drained soil.",
  },
  {
    kind: "garden",
    common: "Cosmos",
    latin: "Cosmos bipinnatus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-25", "06-20"],
    harvest_window: ["06-30", "10-20"],
    spacing_cm: 30,
    frost_sensitive: true,
    summary: "Airy annual with daisy-like blooms that attract pollinators and beneficial insects.",
  },
  {
    kind: "garden",
    common: "Dahlia",
    latin: "Dahlia × hybrida",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["05-15", "06-15"],
    harvest_window: ["07-20", "10-31"],
    spacing_cm: 45,
    frost_sensitive: true,
    summary: "Tubers produce large showy flowers; lift and store tubers after frost in cold regions.",
  },
  {
    kind: "garden",
    common: "Gladiolus",
    latin: "Gladiolus × hortulanus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "06-15"],
    harvest_window: ["07-01", "09-30"],
    spacing_cm: 15,
    frost_sensitive: true,
    summary: "Corms planted in succession yield sword-like stems with colorful spikes.",
  },
  {
    kind: "garden",
    common: "Tulip",
    latin: "Tulipa gesneriana",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["10-01", "11-15"],
    harvest_window: ["04-01", "05-15"],
    spacing_cm: 10,
    frost_sensitive: false,
    summary: "Spring-blooming bulb planted in autumn; replace annually for best displays.",
  },
  {
    kind: "garden",
    common: "Daffodil",
    latin: "Narcissus pseudonarcissus",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["09-15", "11-15"],
    harvest_window: ["03-15", "04-30"],
    spacing_cm: 12,
    frost_sensitive: false,
    summary: "Reliable perennial bulb; allow foliage to die back naturally after bloom.",
  },
  {
    kind: "garden",
    common: "Lily",
    latin: "Lilium hybrid",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["09-15", "11-01"],
    harvest_window: ["06-15", "08-15"],
    spacing_cm: 25,
    frost_sensitive: false,
    summary: "Fragrant summer bulbs; stake tall stems and keep soil evenly moist.",
  },
  {
    kind: "garden",
    common: "Rose",
    latin: "Rosa × hybrida",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["03-15", "05-15"],
    harvest_window: ["05-20", "10-30"],
    spacing_cm: 90,
    frost_sensitive: false,
    summary: "Classic shrub requiring pruning, feeding, and disease management for repeat bloom.",
  },
  {
    kind: "garden",
    common: "Lavender",
    latin: "Lavandula angustifolia",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["04-15", "06-15"],
    harvest_window: ["06-20", "09-01"],
    spacing_cm: 40,
    frost_sensitive: false,
    summary: "Fragrant perennial for borders; prefers alkaline, sharply drained soil.",
  },
  {
    kind: "garden",
    common: "Hydrangea",
    latin: "Hydrangea macrophylla",
    family: "misc",
    sun: "partial-sun",
    sow_outdoors: ["03-15", "05-15"],
    harvest_window: ["06-20", "09-30"],
    spacing_cm: 120,
    frost_sensitive: false,
    summary: "Shrub with mophead blooms; soil pH influences flower color in many cultivars.",
  },
  {
    kind: "garden",
    common: "Peony",
    latin: "Paeonia lactiflora",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["09-15", "10-31"],
    harvest_window: ["05-15", "06-15"],
    spacing_cm: 90,
    frost_sensitive: false,
    summary: "Long-lived perennial producing large fragrant blooms; avoid planting too deep.",
  },
  {
    kind: "garden",
    common: "Iris",
    latin: "Iris germanica",
    family: "misc",
    sun: "full-sun",
    sow_outdoors: ["07-15", "09-15"],
    harvest_window: ["05-01", "06-15"],
    spacing_cm: 45,
    frost_sensitive: false,
    summary: "Rhizomatous perennial with bearded flowers; plant rhizomes shallow for best bloom.",
  },
  {
    kind: "garden",
    common: "Hosta",
    latin: "Hosta sieboldiana",
    family: "misc",
    sun: "partial-shade",
    sow_outdoors: ["04-15", "09-01"],
    harvest_window: ["05-15", "09-30"],
    spacing_cm: 90,
    frost_sensitive: false,
    summary: "Shade-loving foliage plant with bold leaves; protect from slugs in spring.",
  },
];

export const GARDEN_PLANT_CATALOG: GardenPlantCatalogEntry[] = RAW_GARDEN_PLANT_CATALOG.slice(0, 100);
