import type { HouseplantCatalogEntry } from "./types";

const RAW_HOUSEPLANT_CATALOG: HouseplantCatalogEntry[] = [
  {
    kind: "house",
    common: "Spider plant",
    latin: "Chlorophytum comosum",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Arching variegated strappy leaves that tolerate neglect and clean indoor air.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Snake plant",
    latin: "Dracaena trifasciata",
    light: "medium",
    water_interval_days_hint: 21,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Upright sword-like leaves thrive in low light and withstand irregular watering.",
  },
  {
    kind: "house",
    common: "Golden pothos",
    latin: "Epipremnum aureum",
    light: "medium",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Fast-growing trailing vine with golden variegation suited to hanging baskets.",
  },
  {
    kind: "house",
    common: "Heartleaf philodendron",
    latin: "Philodendron hederaceum",
    light: "medium",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Classic trailing aroid with cordate leaves tolerant of a wide range of homes.",
  },
  {
    kind: "house",
    common: "ZZ plant",
    latin: "Zamioculcas zamiifolia",
    light: "low",
    water_interval_days_hint: 21,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Glossy pinnate foliage storing water in rhizomes, ideal for low maintenance rooms.",
  },
  {
    kind: "house",
    common: "Peace lily",
    latin: "Spathiphyllum wallisii",
    light: "medium",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Shade-loving plant producing white spathes when kept evenly moist and humid.",
  },
  {
    kind: "house",
    common: "Monstera deliciosa",
    latin: "Monstera deliciosa",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Large fenestrated leaves lend a tropical look and appreciate support as they climb.",
  },
  {
    kind: "house",
    common: "Swiss cheese vine",
    latin: "Monstera adansonii",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Delicate perforated foliage ideal for trailing or training onto a moss pole.",
  },
  {
    kind: "house",
    common: "Chinese evergreen",
    latin: "Aglaonema commutatum",
    light: "low",
    water_interval_days_hint: 9,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Broad variegated leaves thrive in dim rooms and prefer evenly moist soil.",
  },
  {
    kind: "house",
    common: "Rubber plant",
    latin: "Ficus elastica",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Thick glossy leaves on upright trunks suit bright corners with occasional wiping.",
  },
  {
    kind: "house",
    common: "Fiddle-leaf fig",
    latin: "Ficus lyrata",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Statement tree with violin-shaped leaves that needs consistent moisture and light.",
  },
  {
    kind: "house",
    common: "Areca palm",
    latin: "Dypsis lutescens",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Graceful clumping palm with feathery fronds that loves humidity and regular feeds.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Parlor palm",
    latin: "Chamaedorea elegans",
    light: "low",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Compact palm tolerating shade, perfect for desks and tabletops.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Kentia palm",
    latin: "Howea forsteriana",
    light: "medium",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Elegant arching palm fronds thrive in bright filtered light with moderate watering.",
  },
  {
    kind: "house",
    common: "Ponytail palm",
    latin: "Beaucarnea recurvata",
    light: "bright-indirect",
    water_interval_days_hint: 21,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Bulbous caudex stores water while strap-like leaves cascade for a sculptural look.",
  },
  {
    kind: "house",
    common: "Majesty palm",
    latin: "Ravenea rivularis",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Fast-growing palm that demands abundant humidity and consistent moisture.",
  },
  {
    kind: "house",
    common: "Bamboo palm",
    latin: "Chamaedorea seifrizii",
    light: "medium",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Clustering stems resemble bamboo canes and filter indoor air effectively.",
  },
  {
    kind: "house",
    common: "Bird of paradise",
    latin: "Strelitzia nicolai",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Large paddle leaves create a tropical backdrop; enjoys bright rooms and misting.",
  },
  {
    kind: "house",
    common: "Aloe vera",
    latin: "Aloe barbadensis miller",
    light: "full-sun",
    water_interval_days_hint: 18,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Succulent rosettes store gel-rich leaves that prefer bright sun and sandy soil.",
  },
  {
    kind: "house",
    common: "Jade plant",
    latin: "Crassula ovata",
    light: "bright-indirect",
    water_interval_days_hint: 14,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Tree-form succulent with coin-like leaves that thrives on bright windowsills.",
  },
  {
    kind: "house",
    common: "Zebra haworthia",
    latin: "Haworthiopsis fasciata",
    light: "bright-indirect",
    water_interval_days_hint: 18,
    humidity: "low",
    feeding_interval_weeks: 12,
    summary: "Compact succulent with striped leaves that tolerates low watering and tight pots.",
  },
  {
    kind: "house",
    common: "Zebra plant",
    latin: "Aphelandra squarrosa",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Boldly striped foliage with yellow bracts that needs warmth and humidity.",
  },
  {
    kind: "house",
    common: "Prayer plant",
    latin: "Maranta leuconeura",
    light: "medium",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Colorful folding leaves follow daily light cycles and crave consistent moisture.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Pinstripe calathea",
    latin: "Calathea ornata",
    light: "medium",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Showy striped foliage that demands warm humid air and soft, filtered water.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Stromanthe triostar",
    latin: "Stromanthe sanguinea",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Pink, cream, and green leaves offer dramatic color but need high humidity.",
  },
  {
    kind: "house",
    common: "Corn plant",
    latin: "Dracaena fragrans",
    light: "medium",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Cane-form dracaena with arching leaves suited to hallways and tolerant of shade.",
  },
  {
    kind: "house",
    common: "Dragon tree",
    latin: "Dracaena marginata",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Slender trunks topped with strappy leaves adapt well to bright living rooms.",
  },
  {
    kind: "house",
    common: "Song of India",
    latin: "Dracaena reflexa",
    light: "bright-indirect",
    water_interval_days_hint: 9,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Variegated dracaena cultivar with lime-edged leaves liking bright filtered light.",
  },
  {
    kind: "house",
    common: "Yucca cane",
    latin: "Yucca gigantea",
    light: "full-sun",
    water_interval_days_hint: 14,
    humidity: "low",
    feeding_interval_weeks: 12,
    summary: "Architectural rosettes on woody trunks thrive in sunny rooms with gritty soil.",
  },
  {
    kind: "house",
    common: "Umbrella tree",
    latin: "Schefflera arboricola",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Palmate glossy leaves form dense canopies; prune for shape and moderate size.",
  },
  {
    kind: "house",
    common: "Boston fern",
    latin: "Nephrolepis exaltata",
    light: "medium",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Feathery fronds spill from baskets and appreciate frequent misting.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Bird's-nest fern",
    latin: "Asplenium nidus",
    light: "medium",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Glossy fronds emerge from a central rosette that likes warmth and gentle watering.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Maidenhair fern",
    latin: "Adiantum raddianum",
    light: "bright-indirect",
    water_interval_days_hint: 3,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Delicate fan-shaped leaflets require steady moisture and humid air to thrive.",
  },
  {
    kind: "house",
    common: "Staghorn fern",
    latin: "Platycerium bifurcatum",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Epiphytic fern mounted on boards; soak or mist regularly to mimic rainforest.",
  },
  {
    kind: "house",
    common: "Asparagus fern",
    latin: "Asparagus densiflorus",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Fine-textured foliage forms soft mounds; tolerates brighter light than true ferns.",
  },
  {
    kind: "house",
    common: "Kangaroo paw fern",
    latin: "Microsorum diversifolium",
    light: "medium",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Glossy lobed fronds trail over pot edges and enjoy consistent humidity.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "English ivy",
    latin: "Hedera helix",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Classic trailing vine that appreciates cool rooms and regular misting.",
  },
  {
    kind: "house",
    common: "Swedish ivy",
    latin: "Plectranthus verticillatus",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Round scalloped leaves on trailing stems emit a mild herbal scent when brushed.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Chinese money plant",
    latin: "Pilea peperomioides",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Saucer-shaped leaves on upright petioles create a cheerful, modern silhouette.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Baby rubber plant",
    latin: "Peperomia obtusifolia",
    light: "medium",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Compact succulent-like foliage perfect for desks and tolerant of moderate neglect.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Watermelon peperomia",
    latin: "Peperomia argyreia",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Striped leaves mimic watermelon rinds; avoid direct sun to prevent scorching.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Nerve plant",
    latin: "Fittonia albivenis",
    light: "low",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Tiny veined leaves prefer terrarium-like humidity and faint light.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Polka dot plant",
    latin: "Hypoestes phyllostachya",
    light: "medium",
    water_interval_days_hint: 4,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Speckled foliage adds color; pinch tips frequently to keep plants bushy.",
  },
  {
    kind: "house",
    common: "String of hearts",
    latin: "Ceropegia woodii",
    light: "bright-indirect",
    water_interval_days_hint: 12,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Silver-marbled heart leaves trail gracefully and like to dry between waterings.",
  },
  {
    kind: "house",
    common: "String of pearls",
    latin: "Curio rowleyanus",
    light: "bright-indirect",
    water_interval_days_hint: 12,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Bead-like succulents tumble over pot edges; ensure excellent drainage.",
  },
  {
    kind: "house",
    common: "Wax plant",
    latin: "Hoya carnosa",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Thick vining leaves produce fragrant starry blooms when pot-bound in bright light.",
  },
  {
    kind: "house",
    common: "Sweetheart hoya",
    latin: "Hoya kerrii",
    light: "bright-indirect",
    water_interval_days_hint: 14,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Heart-shaped succulent leaves often sold as single-leaf gifts; slow but hardy.",
  },
  {
    kind: "house",
    common: "Flamingo flower",
    latin: "Anthurium andraeanum",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Shiny heart leaves and colorful spathes bloom with humidity and filtered light.",
  },
  {
    kind: "house",
    common: "Scarlet star bromeliad",
    latin: "Guzmania lingulata",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Colorful central rosette holds water in its cup; flush regularly to avoid rot.",
  },
  {
    kind: "house",
    common: "Blushing bromeliad",
    latin: "Neoregelia carolinae",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Flat rosette flashes vivid colors when grown bright; keep central tank topped up.",
  },
  {
    kind: "house",
    common: "Air plant",
    latin: "Tillandsia ionantha",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Epiphytic bromeliad needing regular misting or soaking and bright filtered light.",
  },
  {
    kind: "house",
    common: "Sago palm",
    latin: "Cycas revoluta",
    light: "bright-indirect",
    water_interval_days_hint: 14,
    humidity: "medium",
    feeding_interval_weeks: 10,
    summary: "Slow-growing cycad with stiff fronds; allow soil to dry between deep waterings.",
  },
  {
    kind: "house",
    common: "Norfolk Island pine",
    latin: "Araucaria heterophylla",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Soft needled evergreen for bright cool rooms; dislikes dry heated air.",
  },
  {
    kind: "house",
    common: "Croton",
    latin: "Codiaeum variegatum",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Vividly variegated leaves need steady warmth, humidity, and bright light.",
  },
  {
    kind: "house",
    common: "Japanese aralia",
    latin: "Fatsia japonica",
    light: "medium",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Bold palmate leaves provide architectural foliage in bright but cool rooms.",
  },
  {
    kind: "house",
    common: "Tree philodendron",
    latin: "Thaumatophyllum bipinnatifidum",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Deeply lobed leaves form a tropical clump; allow space and provide support stakes.",
  },
  {
    kind: "house",
    common: "Philodendron 'Birkin'",
    latin: "Philodendron 'Birkin'",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Variegated pinstripes on compact leaves need stable warmth and bright filtered light.",
  },
  {
    kind: "house",
    common: "Satin pothos",
    latin: "Scindapsus pictus",
    light: "medium",
    water_interval_days_hint: 8,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Velvety silver-dappled leaves trail gracefully; allow top inch to dry out.",
  },
  {
    kind: "house",
    common: "Arrowhead vine",
    latin: "Syngonium podophyllum",
    light: "medium",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Juvenile arrow-shaped leaves climb or trail; likes humidity and regular pruning.",
  },
  {
    kind: "house",
    common: "African mask plant",
    latin: "Alocasia x amazonica",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Dramatic dark leaves with bold veins thrive in warm, humid, bright spots.",
  },
  {
    kind: "house",
    common: "Elephant ear",
    latin: "Colocasia esculenta",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Huge heart-shaped leaves provide tropical impact and need ample moisture.",
  },
  {
    kind: "house",
    common: "Fancy-leaf caladium",
    latin: "Caladium bicolor",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Colorful thin leaves require warmth and humidity; go dormant in winter.",
  },
  {
    kind: "house",
    common: "Polka dot begonia",
    latin: "Begonia maculata",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Silver-spotted angel-wing leaves with red undersides prefer bright filtered light.",
  },
  {
    kind: "house",
    common: "Rex begonia",
    latin: "Begonia rex-cultorum",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Vivid patterned foliage thrives in humid terrarium-like conditions.",
  },
  {
    kind: "house",
    common: "Angel wing begonia",
    latin: "Begonia coccinea",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Cane-like stems produce pendant clusters of flowers in bright rooms.",
  },
  {
    kind: "house",
    common: "Zonal geranium",
    latin: "Pelargonium hortorum",
    light: "full-sun",
    water_interval_days_hint: 5,
    humidity: "low",
    feeding_interval_weeks: 4,
    summary: "Sun-loving flowering plant often overwintered indoors on bright sills.",
  },
  {
    kind: "house",
    common: "African violet",
    latin: "Saintpaulia ionantha",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Fuzzy leaves and frequent blooms thrive under steady light and bottom watering.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Cape primrose",
    latin: "Streptocarpus hybrid",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Orchid-like blooms over strap leaves; prefers cool bright rooms and light feeds.",
  },
  {
    kind: "house",
    common: "Flaming Katy",
    latin: "Kalanchoe blossfeldiana",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Succulent foliage bears clusters of flowers; allow soil to dry between drinks.",
  },
  {
    kind: "house",
    common: "Mexican snowball echeveria",
    latin: "Echeveria elegans",
    light: "full-sun",
    water_interval_days_hint: 18,
    humidity: "low",
    feeding_interval_weeks: 12,
    summary: "Rosette succulent preferring bright sun and infrequent watering.",
  },
  {
    kind: "house",
    common: "Burro's tail",
    latin: "Sedum morganianum",
    light: "bright-indirect",
    water_interval_days_hint: 18,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Trailing succulent stems covered in plump leaves require gentle handling.",
  },
  {
    kind: "house",
    common: "Ghost plant",
    latin: "Graptopetalum paraguayense",
    light: "full-sun",
    water_interval_days_hint: 18,
    humidity: "low",
    feeding_interval_weeks: 12,
    summary: "Pale rosettes blush in sun; thrives in gritty mix with rare watering.",
  },
  {
    kind: "house",
    common: "String of tears",
    latin: "Curio herreanus",
    light: "bright-indirect",
    water_interval_days_hint: 14,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Trailing bead-like leaves with purple undersides enjoy bright light and dryness.",
  },
  {
    kind: "house",
    common: "African milk tree",
    latin: "Euphorbia trigona",
    light: "full-sun",
    water_interval_days_hint: 21,
    humidity: "low",
    feeding_interval_weeks: 12,
    summary: "Tall candelabra succulent tolerant of bright sun and sparse watering.",
  },
  {
    kind: "house",
    common: "Golden barrel cactus",
    latin: "Echinocactus grusonii",
    light: "full-sun",
    water_interval_days_hint: 28,
    humidity: "low",
    feeding_interval_weeks: 16,
    summary: "Round cactus with golden spines requiring maximal light and minimal water.",
  },
  {
    kind: "house",
    common: "Christmas cactus",
    latin: "Schlumbergera truncata",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Holiday-flowering cactus prefers bright shade and likes to dry slightly between drinks.",
  },
  {
    kind: "house",
    common: "Easter cactus",
    latin: "Hatiora gaertneri",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Segmented stems bloom in spring; keep evenly moist during growth.",
  },
  {
    kind: "house",
    common: "Crown of thorns",
    latin: "Euphorbia milii",
    light: "full-sun",
    water_interval_days_hint: 14,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Thorny succulent shrub with colorful bracts, thriving in bright sun.",
  },
  {
    kind: "house",
    common: "Moth orchid",
    latin: "Phalaenopsis hybrid",
    light: "bright-indirect",
    water_interval_days_hint: 9,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Long-lasting blooms on arching spikes; water sparingly and avoid crown rot.",
  },
  {
    kind: "house",
    common: "Boat orchid",
    latin: "Cymbidium hybrid",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Cool-growing orchid producing sprays of waxy flowers when kept bright.",
  },
  {
    kind: "house",
    common: "Nobile dendrobium",
    latin: "Dendrobium nobile",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Cane-type orchid with fragrant blooms; needs bright light and winter rest.",
  },
  {
    kind: "house",
    common: "Dancing lady orchid",
    latin: "Oncidium hybrid",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Sprays of tiny blooms and strappy leaves prefer airy mix and regular misting.",
  },
  {
    kind: "house",
    common: "Pansy orchid",
    latin: "Miltoniopsis hybrid",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Cool-growing orchid with large flat blooms; dislikes heat and dry roots.",
  },
  {
    kind: "house",
    common: "Tropical pitcher plant",
    latin: "Nepenthes ventricosa",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Carnivorous vine bearing pitchers; requires pure water and humid warmth.",
  },
  {
    kind: "house",
    common: "Venus flytrap",
    latin: "Dionaea muscipula",
    light: "full-sun",
    water_interval_days_hint: 3,
    humidity: "high",
    feeding_interval_weeks: 0,
    summary: "Bog-dwelling carnivore needing rainwater and bright sun with winter dormancy.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Dwarf banana",
    latin: "Musa acuminata 'Dwarf Cavendish'",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Fast-growing tropical with large leaves; keep soil moist and feed regularly.",
  },
  {
    kind: "house",
    common: "Meyer lemon",
    latin: "Citrus x meyeri",
    light: "full-sun",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Fragrant blossoms and small fruit indoors when given bright light and citrus feed.",
  },
  {
    kind: "house",
    common: "Calamondin orange",
    latin: "Citrus x microcarpa",
    light: "full-sun",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Compact citrus bearing abundant tart fruits; needs bright sun and steady feeding.",
  },
  {
    kind: "house",
    common: "Bay laurel",
    latin: "Laurus nobilis",
    light: "bright-indirect",
    water_interval_days_hint: 8,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Aromatic leaves for cooking; prefers bright light and good air flow.",
  },
  {
    kind: "house",
    common: "Rosemary",
    latin: "Salvia rosmarinus",
    light: "full-sun",
    water_interval_days_hint: 5,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Evergreen herb needing bright sun, sharp drainage, and light watering.",
  },
  {
    kind: "house",
    common: "Lavender",
    latin: "Lavandula angustifolia",
    light: "full-sun",
    water_interval_days_hint: 6,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Fragrant flowers and silvery foliage thrive on sun and dry air indoors.",
  },
  {
    kind: "house",
    common: "Scented geranium",
    latin: "Pelargonium graveolens",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "low",
    feeding_interval_weeks: 6,
    summary: "Aromatic leaves release perfume; let soil dry slightly between waterings.",
  },
  {
    kind: "house",
    common: "Common thyme",
    latin: "Thymus vulgaris",
    light: "full-sun",
    water_interval_days_hint: 6,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Low-growing herb with woody stems; needs bright sun and excellent drainage.",
  },
  {
    kind: "house",
    common: "Greek oregano",
    latin: "Origanum vulgare subsp. hirtum",
    light: "full-sun",
    water_interval_days_hint: 6,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Pungent culinary herb that prefers bright light and dries quickly between drinks.",
  },
  {
    kind: "house",
    common: "Garden sage",
    latin: "Salvia officinalis",
    light: "full-sun",
    water_interval_days_hint: 6,
    humidity: "low",
    feeding_interval_weeks: 8,
    summary: "Woody herb with grey leaves; enjoys sunny sills and careful watering.",
  },
  {
    kind: "house",
    common: "Sweet basil",
    latin: "Ocimum basilicum",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Tender annual herb; pinch regularly and keep soil evenly moist in bright light.",
  },
  {
    kind: "house",
    common: "Spearmint",
    latin: "Mentha spicata",
    light: "bright-indirect",
    water_interval_days_hint: 3,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Vigorous herb needing frequent watering; best kept in containers to contain roots.",
  },
  {
    kind: "house",
    common: "Lemon balm",
    latin: "Melissa officinalis",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Citrus-scented leaves for teas; trim often and keep soil lightly moist.",
  },
  {
    kind: "house",
    common: "Chives",
    latin: "Allium schoenoprasum",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Hollow leaves with mild onion flavor; snip frequently to encourage fresh growth.",
  },
  {
    kind: "house",
    common: "Parsley",
    latin: "Petroselinum crispum",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Biennial herb; keep evenly moist and harvest outer stems first.",
  },
  {
    kind: "house",
    common: "Cilantro",
    latin: "Coriandrum sativum",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Cool-season herb that bolts in heat; sow successionally for constant supply.",
  },
  {
    kind: "house",
    common: "Lemongrass",
    latin: "Cymbopogon citratus",
    light: "full-sun",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Tropical grass with citrus scent; requires bright light and generous watering.",
  },
  {
    kind: "house",
    common: "Stevia",
    latin: "Stevia rebaudiana",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Sweet-leaved herb for teas; needs warmth and moderate moisture.",
  },
  {
    kind: "house",
    common: "Bay rum tree",
    latin: "Pimenta racemosa",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Aromatic Caribbean tree with glossy leaves; prune to maintain compact form.",
  },
  {
    kind: "house",
    common: "Sweet olive",
    latin: "Osmanthus fragrans",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Fragrant blooms perfume rooms; prefers bright light and even moisture.",
  },
  {
    kind: "house",
    common: "Gardenia",
    latin: "Gardenia jasminoides",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Glossy leaves and scented flowers; needs acidic soil, humidity, and stable care.",
  },
  {
    kind: "house",
    common: "Camellia",
    latin: "Camellia japonica",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Winter-blooming shrub; prefers cool bright rooms and acidic soil.",
  },
  {
    kind: "house",
    common: "Tea plant",
    latin: "Camellia sinensis",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Leaves used for tea; thrives in acidic mix with regular watering and pruning.",
  },
  {
    kind: "house",
    common: "Coffee plant",
    latin: "Coffea arabica",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Glossy evergreen with fragrant blooms; keep evenly moist and provide humidity.",
  },
  {
    kind: "house",
    common: "Pepperomia pixie lime",
    latin: "Peperomia deppeana",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Compact mound of lime-green leaves suited to terrariums and bright desks.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Ficus benjamina",
    latin: "Ficus benjamina",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Graceful weeping fig tree that reacts to change; keep light consistent.",
  },
  {
    kind: "house",
    common: "Weeping fig 'Danielle'",
    latin: "Ficus benjamina 'Danielle'",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Dark-leaved cultivar tolerant of pruning; rotate regularly for balanced growth.",
  },
  {
    kind: "house",
    common: "Pilea glauca",
    latin: "Pilea libanensis",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Tiny cascading leaves form dense mats; thrives in terrariums or hanging pots.",
  },
  {
    kind: "house",
    common: "Baby's tears",
    latin: "Soleirolia soleirolii",
    light: "medium",
    water_interval_days_hint: 3,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Minute leaves create lush carpets; keep soil consistently moist.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Club moss",
    latin: "Selaginella kraussiana",
    light: "low",
    water_interval_days_hint: 3,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Mossy fern ally for terrariums; needs constant moisture and humidity.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Sensitive plant",
    latin: "Mimosa pudica",
    light: "bright-indirect",
    water_interval_days_hint: 4,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Leaves fold on touch; keep warm and moist with bright filtered light.",
  },
  {
    kind: "house",
    common: "Lucky bamboo",
    latin: "Dracaena sanderiana",
    light: "low",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 8,
    summary: "Often grown in water; change water regularly and keep out of direct sun.",
  },
  {
    kind: "house",
    common: "Pothos 'Neon'",
    latin: "Epipremnum aureum 'Neon'",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Chartreuse leaves brighten low-light corners with minimal fuss.",
  },
  {
    kind: "house",
    common: "Philodendron Brasil",
    latin: "Philodendron hederaceum 'Brasil'",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Green and lime variegated vine; pinch to encourage fullness.",
  },
  {
    kind: "house",
    common: "Silver sword philodendron",
    latin: "Philodendron hastatum",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Metallic arrow-shaped leaves climb eagerly and enjoy humid warmth.",
  },
  {
    kind: "house",
    common: "Blue star fern",
    latin: "Phlebodium aureum",
    light: "medium",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "Powdery blue fronds with wavy edges; prefers peat-free airy mix and humidity.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Rattlesnake calathea",
    latin: "Goeppertia insignis",
    light: "medium",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Elongated patterned leaves with purple undersides enjoy warm, humid environments.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Cast iron plant",
    latin: "Aspidistra elatior",
    light: "low",
    water_interval_days_hint: 14,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Nearly indestructible foliage plant coping with shade, drafts, and irregular care.",
  },
  {
    kind: "house",
    common: "Swiss cheese plant 'Thai Constellation'",
    latin: "Monstera deliciosa 'Thai Constellation'",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Variegated monstera needing stable warmth, humidity, and careful watering.",
  },
  {
    kind: "house",
    common: "Philodendron pink princess",
    latin: "Philodendron erubescens 'Pink Princess'",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Dusky leaves splashed with pink variegation; requires bright filtered light.",
  },
  {
    kind: "house",
    common: "Mini monstera",
    latin: "Rhaphidophora tetrasperma",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Fast-climbing aroid with split leaves; provide moss pole and regular feeding.",
  },
  {
    kind: "house",
    common: "Dragon scale alocasia",
    latin: "Alocasia baginda 'Dragon Scale'",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Textured metallic leaves with prominent veining; likes warmth and humidity.",
  },
  {
    kind: "house",
    common: "Philodendron micans",
    latin: "Philodendron hederaceum var. hederaceum",
    light: "medium",
    water_interval_days_hint: 6,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Velvety trailing leaves with bronzy sheen; tolerant of lower light conditions.",
  },
  {
    kind: "house",
    common: "Pothos 'Manjula'",
    latin: "Epipremnum aureum 'Manjula'",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Cream-splashed leaves need bright filtered light to maintain variegation.",
  },
  {
    kind: "house",
    common: "Homalomena 'Selby'",
    latin: "Homalomena wallisii",
    light: "medium",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Compact aroid with mottled leaves enjoying warm, evenly moist soil.",
  },
  {
    kind: "house",
    common: "Aglaonema 'Silver Bay'",
    latin: "Aglaonema commutatum 'Silver Bay'",
    light: "low",
    water_interval_days_hint: 9,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Silver-tinged leaves tolerate dim corners and irregular watering.",
  },
  {
    kind: "house",
    common: "Peperomia hope",
    latin: "Peperomia tetraphylla",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Trailing succulent-like peperomia with coin leaves ideal for hanging planters.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Button fern",
    latin: "Pellaea rotundifolia",
    light: "medium",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Rounded leaflets on arching fronds; tolerates slightly drier air than many ferns.",
    pet_safe: true,
  },
  {
    kind: "house",
    common: "Hoya pubicalyx",
    latin: "Hoya pubicalyx",
    light: "bright-indirect",
    water_interval_days_hint: 10,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Vigorous vining hoya with speckled leaves and clusters of fragrant blooms.",
  },
  {
    kind: "house",
    common: "Dischidia ruscifolia",
    latin: "Dischidia ruscifolia",
    light: "bright-indirect",
    water_interval_days_hint: 7,
    humidity: "high",
    feeding_interval_weeks: 6,
    summary: "String of hearts-like vine with heart-shaped leaves; thrives in humidity.",
  },
  {
    kind: "house",
    common: "Lipstick plant",
    latin: "Aeschynanthus radicans",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Tubular red flowers emerge from glossy foliage when given bright light and humidity.",
  },
  {
    kind: "house",
    common: "Goldfish plant",
    latin: "Nematanthus gregarius",
    light: "bright-indirect",
    water_interval_days_hint: 6,
    humidity: "high",
    feeding_interval_weeks: 4,
    summary: "Glossy trailing stems produce orange blooms shaped like leaping fish.",
  },
  {
    kind: "house",
    common: "Purple shamrock",
    latin: "Oxalis triangularis",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Triangular purple leaves close at night; allow brief dormancy if growth slows.",
    pet_safe: false,
  },
  {
    kind: "house",
    common: "Turtle vine",
    latin: "Callisia repens",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 6,
    summary: "Tiny variegated leaves on cascading stems; pinch frequently to stay compact.",
  },
  {
    kind: "house",
    common: "Tradescantia zebrina",
    latin: "Tradescantia zebrina",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Striped purple foliage trails quickly; bright light keeps colors vivid.",
  },
  {
    kind: "house",
    common: "Tradescantia nanouk",
    latin: "Tradescantia albiflora 'Nanouk'",
    light: "bright-indirect",
    water_interval_days_hint: 5,
    humidity: "medium",
    feeding_interval_weeks: 4,
    summary: "Pink-striped foliage on chunky stems; allow topsoil to dry between waterings.",
  },
  {
    kind: "house",
    common: "Ponytail palm bonsai",
    latin: "Beaucarnea recurvata 'Nolina'",
    light: "bright-indirect",
    water_interval_days_hint: 21,
    humidity: "low",
    feeding_interval_weeks: 10,
    summary: "Miniature ponytail palm suited to bonsai containers and sparse watering.",
  },
];

export const HOUSEPLANT_CATALOG: HouseplantCatalogEntry[] = RAW_HOUSEPLANT_CATALOG.slice(0, 100);
